import streamlit as st

TERMS_OF_SERVICE = """
## ⚖️ LogeekMind Terms of Service (ToS)
**(Effective Date: November 24, 2025)**

---

### **1. Acceptance of Terms**

By accessing and using the LogeekMind web application (the "Service"), you agree to be bound by these Terms of Service (the "Terms"). If you do not agree to the Terms, you must not use the Service.

### **2. User Content & Intellectual Property**

* **2.1. Ownership of Input:** You retain all ownership rights in the lecture audio, notes, and text prompts you submit to the Service ("Input Content").
* **2.2. Ownership of Output:** LogeekMind grants you a worldwide, royalty-free, perpetual license to use the content generated by the AI (the quizzes, summaries, "Output Content") for your personal, non-commercial, educational use.
* **2.3. AI Content Similarity:** You acknowledge that due to the nature of AI models, the Output Content may not be unique, and other users may receive similar or identical Output Content.

### **3. Acceptable Use Policy**

You agree not to use LogeekMind to:
* Submit any content that is illegal, defamatory, harassing, or violates any third party's rights.
* Attempt to reverse engineer, hack, or disrupt the integrity or performance of the Service or its underlying AI APIs.
* Use the Output Content for any purpose that could have a legal or material impact on any person (e.g., credit, educational, legal decisions).

### **4. AI Accuracy Disclaimer (Limitation of Liability)**

**THE MOST IMPORTANT CLAUSE**

* **4.1. AI Accuracy:** You understand and agree that the **Artificial Intelligence technology is probabilistic in nature**, and the Output Content generated by the Service (including quizzes and summaries) may occasionally contain **errors, inaccuracies, or "hallucinations."**
* **4.2. No Professional Advice:** The Service is provided for **educational assistance and supplementary study only** and is **not a substitute for professional advice** from a teacher, professor, or qualified professional.
* **4.3. User Responsibility:** You are solely responsible for evaluating the accuracy, completeness, and appropriateness of the Output Content for your use, and you agree that **you will not rely on the Output Content as the sole source of factual information.**
* **4.4. Indemnification:** You agree to indemnify and hold LogeekMind harmless from any claims arising out of your reliance on or misuse of the Output Content.

### **5. Termination**

LogeekMind reserves the right to suspend or terminate your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.

### **6. General Disclaimer**

The Service is provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by applicable law, LogeekMind disclaims all warranties. LogeekMind shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
"""

st.title("LogeekMind Terms of Service")
st.markdown(TERMS_OF_SERVICE, unsafe_allow_html=False)

if st.button("Back to Home page"):
    st.switch_page("LogeekMind.py")